on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create wasm Pre-release


jobs:

  publish-wasm:
    name: Publish wasm 
    needs: release
    runs-on: ubuntu-latest 
    container:
      image: chainxcn/srtools:nightly-2020-09-30
      volumes:
        - ${{ github.workspace }}:/build
    env:
      PACKAGE: chainx-runtime
      RUSTC_VERSION: nightly-2020-09-30

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        cd /build
        pwd
        ls -la 
        build --json | tee srtool_output.json

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Upload json to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: srtool_output.json
        asset_name: chainx-${{ steps.get_version.outputs.VERSION }}.build.json
        tag: ${{ github.ref }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/srtool/release/wbuild/chainx-runtime/chainx_runtime.compact.wasm
        asset_name: chainx-${{ steps.get_version.outputs.VERSION }}.wasm
        tag: ${{ github.ref }}
